DROP TABLE IF EXISTS families;
CREATE TABLE IF NOT EXISTS families (
  id INTEGER PRIMARY KEY,
  name VARCHAR NOT NULL,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS models;
CREATE TABLE IF NOT EXISTS models (
    id INTEGER PRIMARY KEY,
    name VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS products;
CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY,
    id_family INTEGER NOT NULL,
    id_model INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (id_family) REFERENCES families (id) ON DELETE CASCADE,
    FOREIGN KEY (id_model) REFERENCES models (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS products_options;
CREATE TABLE IF NOT EXISTS products_options (
    id INTEGER PRIMARY KEY,
    id_product INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    image_url TEXT,
    price DOUBLE(10, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (id_product) REFERENCES products (id) ON DELETE CASCADE
);
